In [2]:
import numpy as np

In [3]:
a = [10,20,30,40]
print(a)

[10, 20, 30, 40]


In [4]:
# np.array() is used to convert python list to a numpy array
b = np.array(a)
print(b)





[10 20 30 40]


In [5]:
a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [15]:
# We can perform mathematical operations like additions, subtraction,division and multiplication on an array.
a=a+10
print(a.shape) # Shape of Array
print(type(a)) # internal data type


(3,)
<class 'numpy.ndarray'>


In [16]:
b = np.array([10.5,20.2,30.6])
print(type(b))


<class 'numpy.ndarray'>


In [17]:
a = np.array([1,2,3,4,5], ndmin = 2)
print(a)


[[1 2 3 4 5]]


In [18]:
a = np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [19]:
# 2 dim array
c = np.array([(1,2,3),
 (4,5,6)])
print(c.shape)


(2, 3)


In [20]:
# 3 dim array
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d.shape)
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)


(2, 2, 3)
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [21]:
# NumPy also provides a reshape function to resize an array.
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
# ndarray.ndim attribute returns the number of array dimensions.
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a.ndim) # 1 dimensional array
a = np.array([(1,2,3),(4,5,6)])
print(a)
a.reshape(3,2)


[1 2 3 4 5 6 7 8]
1
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# numpy.zeros Returns a new array of specified size, filled with zeros.
np.zeros((2,2))
np.zeros((2,2), dtype=np.int16)


array([[0, 0],
       [0, 0]], dtype=int16)

In [28]:
# numpy.ones Returns a new array of specified size, filled with ones.
np.ones(5)
np.ones([2,2], dtype = int)



array([[1, 1],
       [1, 1]])

In [29]:
# numpy.asarray is used to convert Python sequence into ndarray
a = [1,2,3]
b = np.asarray(a)# convert list to ndarray
print(b)


[1 2 3]


In [30]:
b = np.asarray(a, dtype = float) # dtype is set
print(b)


[1. 2. 3.]


In [31]:
a = (1,2,3)
b = np.asarray(a)# ndarray from tuple
print(b)


[1 2 3]


In [33]:
a = [(1,2,3),(4,5)]
b = np.asarray(a) # ndarray from list of tuples
print(b)


[(1, 2, 3) (4, 5)]


/tmp/ipykernel_12499/1751748636.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.asarray(a) # ndarray from list of tuples


In [35]:
# numpy.arange is used to print the sequence of values numpy.arange(start, stop,step)
np.arange(5)
np.arange(5, dtype = float)
np.arange(1, 11)
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [36]:
# numpy.linspace is similar to arange(),instead of step size, works with length
# Syntax: numpy.linspace(start, stop, num, endpoint, retstep, dtype)
np.linspace(10,20,5)
np.linspace(10,20, 5, endpoint = False)
np.linspace(1.0, 5.0, 10)
np.linspace(1.0, 5.0, 5, endpoint=False)
np.linspace(1,2,5, retstep = True)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [38]:
# Indexing & Slicing:
# ===================
a = np.arange(10)
slice(2,7,2)
a[2:7:2]
a[5] # slice single item
a[2:] # slice items starting from index
a[2:5]# slice items between indexes
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a[1:] # slice items starting from index
a[...,1] # this returns array of items in the second column
a[1,...] # Now we will slice all items from the second row

array([3, 4, 5])

In [41]:
a[...,1:] # Now we will slice all items from column 1 onwards
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x[1:4,1:3] # slicing
y = x[1:4,[1,2]] # using advanced index for column
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a+b)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a+b) # b is broadcast to become compatible with a
a.T # Transpose
# Statistical Functions
np.min(a)
np.max(a)
np.mean(a)
np.median(a)
np.std(a)
# Arithmetic operations
np.add(a,b)

[11 22 33 44]
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

In [44]:
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)
np.power(a,2)
# NumPy package contains numpy.linalg module that provides all the functionality required for linear algebra.
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
np.dot(a,b) # [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
np.matmul(a,b)
np.vdot(a,b) # 1*11 + 2*12 + 3*13 + 4*14
np.inner(a,b) # 1*11+2*12, 1*13+2*14, 3*11+4*12, 3*13+4*14
np.linalg.det(a) # Determinant ad-bc
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(x) # 1*(5*9 - 6*8) + 2*(4*9 - 6*7) + 3*(4*8 - 5*7)
# Generate random numbers:
# ========================
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))
# Normal distribution with mean=0 and variance=1 of shape 2,2

[[0.19569717 0.06762281]
 [0.63308999 0.35934923]]


In [45]:
print(np.random.randn(2,2))
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))
# One random number between [0,1)
print(np.random.random())
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4,
0.1]))
# Create the random state
rn = np.random.RandomState(100)
# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[ 0.62562407 -1.81721559]
 [ 0.5015116   0.80207953]]
[[3 7]
 [7 8]]
0.22577110471242623
[[0.66140588 0.28346968]
 [0.22517534 0.30684792]]
['u' 'i' 'a' 'a' 'i' 'a' 'a' 'e' 'u' 'o']
['o' 'a' 'o' 'a' 'a' 'o' 'a' 'o' 'o' 'i']
[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [46]:
# Set the random seed
np.random.seed(100)
# Create random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts : ", counts)

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]
[8 8 3 7 7 0 4 2 5 2]
Unique items :  [0 2 3 4 5 7 8]
Counts :  [1 2 1 1 1 2 2]
